---
system_domain: 148.100.113.139.nip.io 
releases:
  defaults:
    url: docker.io/quarkz
    stemcell:
      os: opensuse
      version: 0.0.80-7.0.0_374.gb8e8e6af 
  staticfile-buildpack:
    url: docker.io/quarkz
    version: 1.5.10
  capi: 
    url: docker.io/quarkz
    version: 1.92.0 
services:
  router:
    externalIPs: ["148.100.113.139"]
  ssh-proxy:
    externalIPs: ["148.100.113.139"]
  tcp-router:
    type: LoadBalancer
    externalIPs: ["148.100.113.139"]
    port_range:
      start: 20000
      end: 20008

properties:
  api:
    cloud_controller_ng:
      quarks:
        debug: true

operations:
  inline:
  - type: remove
    path: /instance_groups/name=smoke-tests
#  - type: remove
#    path: /instance_groups/name=api/jobs/name=binary-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=dotnet-core-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=go-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=java-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=nodejs-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=nginx-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=php-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=python-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=ruby-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-staticfile-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=r-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-dotnet-core-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-go-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-java-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-nodejs-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-nginx-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-php-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-python-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-ruby-buildpack
  - type: remove
    path: /instance_groups/name=api/jobs/name=suse-binary-buildpack

  - type: replace
    path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/install_buildpacks
    value:
    - name: staticfile_buildpack
      file: /var/vcap/data/shared-packages/staticfile-buildpack/packages/staticfile-buildpack-cflinuxfs3/staticfile_buildpack-cflinuxfs3-v1.5.10.zip
    - name: binary_buildpack
      file: /var/vcap/data/shared-packages/binary-buildpack/packages/binary-buildpack-cflinuxfs3/binary_buildpack-cflinuxfs3-v1.0.36.zip

features:
  eirini:
    enabled: true
  suse_buildpacks:
    enabled: true
  credhub:
    enabled: false
  embedded_database:
    enabled: false
  external_database:
    enabled: true
    type: mysql
    host: mysql.mysql.svc
    port: 3306
    databases:
      uaa:
        name: uaa
        password: password
        username: root
      cc:
        name: cloud_controller
        password: password
        username: root
      bbs:
        name: diego
        password: password
        username: root
      routing_api:
        name: routing-api
        password: password
        username: root
      policy_server:
        name: network_policy
        password: password
        username: root
      silk_controller:
        name: network_connectivity
        password: password
        username: root
      locket:
        name: locket
        password: password
        username: root
      credhub:
        name: credhub
        password: password
        username: root

eirini:
  opi:
    image_tag: "1.5.0"
    image: quarkz/opi
    metrics_collector_image: quarkz/metrics-collector
    route_collector_image: quarkz/route-collector
    route_pod_informer_image: quarkz/route-pod-informer
    route_statefulset_informer_image: quarkz/route-statefulset-informer
    event_reporter_image: quarkz/event-reporter
    event_reporter_image_tag: "1.5.0"
    staging_reporter_image: quarkz/staging-reporter
    staging_reporter_image_tag: "1.5.0"

    staging:
      downloader_image: quarkz/recipe-downloader #registry.suse.com/cap-staging/recipe-downloader
      downloader_image_tag: 1.5.0-24.1 #"1.5.0-24.1"
      executor_image: quarkz/recipe-executor #registry.suse.com/cap-staging/recipe-executor
      executor_image_tag: 1.5.0-24.1 #"1.5.0-24.1"
      uploader_image: quarkz/recipe-uploader #registry.suse.com/cap-staging/recipe-uploader
      uploader_image_tag: 1.5.0-24.1 #"1.5.0-24.1"

bits:
  global:
    images:
      bits_service: quarkz/bits-service:bits-s390x

eirinix:
  loggregator-bridge:
    image:
      repository: quarkz
      tag: v0.0.0-0.gfd70cac
  persi:
    image:
      repository: quarkz
      tag: v0.0.0-67.ge68b3d3
  persi-broker:
    image:
      repository: quarkz
      tag: v0.0.0-g47355df
    setup-image:
      repository: quarkz
      tag: v0.0.0-ge2799d8
  ssh:
    image:
      repository: quarkz
      tag: v0.0.0-0.ge2ed1ab
  ssh-proxy:
    replicaCount: 0
    image:
      repository: quarkz
      tag: v0.0.0-ge2799d8
    setup-image:
      repository: quarkz
      tag: v0.0.0-ge2799d8
